CREATE TABLE CUSTOMER(
    MEMBER_NO NUMBER PRIMARY KEY,
    MEMBER_ID VARCHAR2(20) NOT NULL,
    MEMBER_PW VARCHAR2(20) NOT NULL,
    MEMBER_NM VARCHAR2(30) NOT NULL,
    MEMBER_SSN CHAR(14) NOT NULL
);

COMMENT ON COLUMN CUSTOMER.MEMBER_NO IS '회원 번호(PK)';
COMMENT ON COLUMN CUSTOMER.MEMBER_ID IS '회원 아이디';
COMMENT ON COLUMN CUSTOMER.MEMBER_PW IS '회원 비밀번호';
COMMENT ON COLUMN CUSTOMER.MEMBER_NM IS '회원 이름';
COMMENT ON COLUMN CUSTOMER.MEMBER_SSN IS '회원 주민번호';

CREATE TABLE DELEVERY_SERVICE (
    RESTAURANT NUMBER PRIMARY KEY,
    RESTAURANT_NAME VARCHAR2(60) NOT NULL
);

INSERT INTO DELEVERY_SERVICE(RESTAURANT, RESTAURANT_NAME) VALUES (1, 'CHINESE_FOOD');
INSERT INTO DELEVERY_SERVICE(RESTAURANT, RESTAURANT_NAME) VALUES (2, 'JAPANESE_FOOD');
INSERT INTO DELEVERY_SERVICE(RESTAURANT, RESTAURANT_NAME) VALUES (3, 'KOREAN_FOOD');
INSERT INTO DELEVERY_SERVICE(RESTAURANT, RESTAURANT_NAME) VALUES (4, 'AMERICAN_FOOD');

CREATE TABLE CHINESE_FOOD (
    RESTAURANT_NUM NUMBER,
    MENU_NUM NUMBER PRIMARY KEY,
    MENU_NAME VARCHAR2(300) NOT NULL ,
    MENU_PRICE VARCHAR2(300) NOT NULL,
    RESTAURANT NUMBER REFERENCES CUSTOMER
);

INSERT INTO CHINESE_FOOD(RESTAURANT_NUM, MENU_NUM, MENU_NAME, MENU_PRICE) 
VALUES (1, 1, '짜장면', '5,000');
INSERT INTO CHINESE_FOOD(RESTAURANT_NUM, MENU_NUM, MENU_NAME, MENU_PRICE) 
VALUES (1, 2, '짬뽕', '6,000');
INSERT INTO CHINESE_FOOD(RESTAURANT_NUM, MENU_NUM, MENU_NAME, MENU_PRICE) 
VALUES (1, 3, '볶음밥', '6,500');
INSERT INTO CHINESE_FOOD(RESTAURANT_NUM, MENU_NUM, MENU_NAME, MENU_PRICE) 
VALUES (1, 4, '탕수육', '13,000');

CREATE TABLE JAPANESE_FOOD (
    RESTAURANT_NUM NUMBER,
    MENU_NUM NUMBER PRIMARY KEY,
    MENU_NAME VARCHAR2(300) NOT NULL ,
    MENU_PRICE VARCHAR2(300) NOT NULL,
    RESTAURANT NUMBER REFERENCES CUSTOMER
);


INSERT INTO JAPANESE_FOOD(RESTAURANT_NUM, MENU_NUM, MENU_NAME, MENU_PRICE) 
VALUES (2, 1, '라멘', '7,000');
INSERT INTO JAPANESE_FOOD(RESTAURANT_NUM, MENU_NUM, MENU_NAME, MENU_PRICE) 
VALUES (2, 2, '모듬초밥', '13,000');
INSERT INTO JAPANESE_FOOD(RESTAURANT_NUM, MENU_NUM, MENU_NAME, MENU_PRICE) 
VALUES (2, 3, '우동', '7,000');
INSERT INTO JAPANESE_FOOD(RESTAURANT_NUM, MENU_NUM, MENU_NAME, MENU_PRICE) 
VALUES (2, 4, '모듬튀김', '10,000');

CREATE TABLE KOREAN_FOOD (
    RESTAURANT_NUM NUMBER,
    MENU_NUM NUMBER PRIMARY KEY,
    MENU_NAME VARCHAR2(300) NOT NULL ,
    MENU_PRICE VARCHAR2(300) NOT NULL,
    RESTAURANT NUMBER REFERENCES CUSTOMER
);

INSERT INTO KOREAN_FOOD(RESTAURANT_NUM, MENU_NUM, MENU_NAME, MENU_PRICE) 
VALUES (3, 1, '김밥', '2,000');
INSERT INTO KOREAN_FOOD(RESTAURANT_NUM, MENU_NUM, MENU_NAME, MENU_PRICE) 
VALUES (3, 2, '불고기 정식', '9,000');
INSERT INTO KOREAN_FOOD(RESTAURANT_NUM, MENU_NUM, MENU_NAME, MENU_PRICE) 
VALUES (3, 3, '김치찌개', '7,000');
INSERT INTO KOREAN_FOOD(RESTAURANT_NUM, MENU_NUM, MENU_NAME, MENU_PRICE) 
VALUES (3, 4, '된장찌개', '7,000');

CREATE TABLE AMERICAN_FOOD (
    RESTAURANT_NUM NUMBER,
    MENU_NUM NUMBER PRIMARY KEY,
    MENU_NAME VARCHAR2(300) NOT NULL ,
    MENU_PRICE VARCHAR2(300) NOT NULL,
    RESTAURANT NUMBER REFERENCES CUSTOMER
);

INSERT INTO AMERICAN_FOOD(RESTAURANT_NUM, MENU_NUM, MENU_NAME, MENU_PRICE) 
VALUES (4, 1, '불고기버거', '6,000');
INSERT INTO AMERICAN_FOOD(RESTAURANT_NUM, MENU_NUM, MENU_NAME, MENU_PRICE) 
VALUES (4, 2, '감자튀김', '3,000');
INSERT INTO AMERICAN_FOOD(RESTAURANT_NUM, MENU_NUM, MENU_NAME, MENU_PRICE) 
VALUES (4, 3, '파스타', '8,000');
INSERT INTO AMERICAN_FOOD(RESTAURANT_NUM, MENU_NUM, MENU_NAME, MENU_PRICE) 
VALUES (4, 4, '피자', '10,000');

CREATE SEQUENCE DELIVERY_NO;
CREATE SEQUENCE CHINESE_FOOD_NO;
CREATE SEQUENCE JAPANESE_FOOD_NO;
CREATE SEQUENCE KOREAN_FOOD_NO;
CREATE SEQUENCE AMERICAN_FOOD_NO;

commit;

ROLLBACK;

ALTER TABLE CUSTOMER ADD MEMBER_ADRESS VARCHAR(300);
ALTER TABLE CUSTOMER ADD MEMBER_PHONE VARCHAR(15);

DROP TABLE DELEVERY_SERVICE;

CREATE TABLE CHINESE_REVIEW (
    REVIEW_NO NUMBER PRIMARY KEY,
    REVIEW_CONTENT VARCHAR2(300) NOT NULL
);

CREATE TABLE JAPANESE_REVIEW (
    REVIEW_NO NUMBER PRIMARY KEY,
    REVIEW_CONTENT VARCHAR2(300) NOT NULL
);

CREATE TABLE KOREAN_REVIEW (
    REVIEW_NO NUMBER PRIMARY KEY,
    REVIEW_CONTENT VARCHAR2(300) NOT NULL
);

CREATE TABLE AMERICAN_REVIEW (
    REVIEW_NO NUMBER PRIMARY KEY,
    REVIEW_CONTENT VARCHAR2(300) NOT NULL
);

CREATE SEQUENCE SEQ_CHINESE_REVIEW_NO;
CREATE SEQUENCE SEQ_JAPANESE_REVIEW_NO;
CREATE SEQUENCE SEQ_KOREAN_REVIEW_NO;
CREATE SEQUENCE SEQ_AMERICAN_REVIEW_NO;
