/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.62
 * Generated at: 2022-06-15 09:57:51 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.views.FAQ;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class personal_002dinfo_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(2);
    _jspx_dependants.put("/WEB-INF/lib/taglibs-standard-impl-1.2.5.jar", Long.valueOf(1652789277576L));
    _jspx_dependants.put("jar:file:/C:/workspace/SemiProject_Achieve/SemiProjectAchieve/src/main/webapp/WEB-INF/lib/taglibs-standard-impl-1.2.5.jar!/META-INF/c.tld", Long.valueOf(1425946270000L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html lang=\"en\">\r\n");
      out.write("<head>\r\n");
      out.write("    <meta charset=\"UTF-8\">\r\n");
      out.write("    <meta http-equiv=\"X-UA-Compatible\" content=\"IE=edge\">\r\n");
      out.write("    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\r\n");
      out.write("    <title>personal-info</title>\r\n");
      out.write("\r\n");
      out.write("    <!-- 헤더, 푸터를 위한 css -->\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/css/header-footer.css\">\r\n");
      out.write("\r\n");
      out.write("    <!-- personal-info 페이지를 위한 css -->\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/css/personal-info.css\">\r\n");
      out.write("    \r\n");
      out.write("\r\n");
      out.write("    <!-- 사이드바 css 포함 -->\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/css/FAQ.css\">\r\n");
      out.write("    <link href=\"https://fonts.googleapis.com/icon?family=Material+Icons\" rel=\"stylesheet\">\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("    \r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("    <main>\r\n");
      out.write("\r\n");
      out.write("        ");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "/WEB-INF/views/common/header.jsp", out, false);
      out.write("\r\n");
      out.write("\r\n");
      out.write("        <section class=\"content\">\r\n");
      out.write("            ");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "/WEB-INF/views/common/sideMenu.jsp", out, false);
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("            <section class=\"main\">\r\n");
      out.write("                <div id=\"body\">\r\n");
      out.write("                    <div id=\"infor-main\">\r\n");
      out.write("        \r\n");
      out.write("                        <div name=\"infor-header\" id=\"infor-first\"> \r\n");
      out.write("                           어취브 개인정보처리방침 \r\n");
      out.write("                        </div>\r\n");
      out.write("        \r\n");
      out.write("                        <div name=\"infor-header\" id=\"start-day\">\r\n");
      out.write("                            (2022-5-25 시행)\r\n");
      out.write("                        </div>\r\n");
      out.write("                        <div name=\"infor-header\" class=\"infor-header\">\r\n");
      out.write("                            어취브 개인정보처리방침\r\n");
      out.write("                        </div>\r\n");
      out.write("        \r\n");
      out.write("                        <div name=\"infor-text\" class=\"infor-text\">\r\n");
      out.write("                            여러분의 개인정보의 안전한 취급은 어취브에게 있어 가장 중요한 일 중 하나입니다. 여러분의 개인정보는 어취브 서비스의 원활한 제공을 위하여 여러분이 동의한 목적과 범위 내에서만 이용됩니다. 법령에 의하거나 여러분이 별도로 동의하지 아니하는 한 어취브가 여러분의 개인정보를 제3자에게 제공하는 일은 결코 없으므로, 안심하셔도 좋습니다. 개인정보처리방침은 항상 공개되어 있으니 지금 당장이 아니더라도 궁금하실 때는 언제든지 읽어보실 수 있습니다. 개인정보처리방침이 바뀐 때에는 여러분이 언제든지 그 내용과 이유를 쉽게 알 수 있도록 공지사항을 통하여 알려 드리겠습니다.\r\n");
      out.write("                        </div>\r\n");
      out.write("        \r\n");
      out.write("                        <div name=\"infor-header\" class=\"infor-header\">\r\n");
      out.write("                            개인정보처리방침의 의의\r\n");
      out.write("                        </div>\r\n");
      out.write("        \r\n");
      out.write("                        <div name=\"infor-text\" class=\"infor-text\">\r\n");
      out.write("                            어취브는 정보통신망 이용촉진 및 정보보호 등에 관한 법률, 개인정보보호법, 통신비밀보호법, 전기통신사업법 등 정보통신서비스제공자가 준수하여야 하는 대한민국의 관계법령 및 개인정보보호 규정, 가이드라인을 준수하며, 관련법령에 의거한 개인정보처리방침을 정하여 이용자의 권익 보호에 최선을 다하고 있습니다. 본 개인정보처리방침은 어취브가 제공하는 서비스(이하 '서비스'라 함)에 적용됩니다.\r\n");
      out.write("                        </div>\r\n");
      out.write("        \r\n");
      out.write("                        <div name=\"infor-header\" class=\"infor-header\">수집하는 개인정보</div>\r\n");
      out.write("                        \r\n");
      out.write("                        \r\n");
      out.write("                        <div name=\"infor-text\" class=\"infor-text\">\r\n");
      out.write("                            어취브는 여러분이 어취브 서비스에 처음 가입할 때 또는 서비스 이용 과정에서 홈페이지 또는 개별 어플리케이션이나 프로그램 등을 통하여 아래와 같은 서비스 제공을 위해 필요한 최소한의 개인정보를 수집하고 있습니다. 어취브는 개별 서비스 이용 과정에서 추가적으로 개인정보 수집이 발생할 경우 수집하는 개인정보에 대하여 별도로 알려 드리며 이에 따라 여러분의 동의를 받고 서비스를 제공하게 됩니다.\r\n");
      out.write("                        </div>\r\n");
      out.write("        \r\n");
      out.write("                        <div name=\"infor-text\" class=\"infor-text\">\r\n");
      out.write("                            [회원 가입 시] 이메일 가입 시(이메일주소, 이름, 비밀번호, 사용자 역할)SNS로 가입 시(이용자 고유 식별자, 이메일주소, 이름, 사용자 역할)휴대전화 번호로 가입 시(휴대전화 번호, 이메일주소, 이름, 비밀번호, 사용자 역할)아이디로 가입 시(아이디, 이메일주소, 이름, 비밀번호, 사용자 역할), 단말기 정보 [만 14세 미만일 시][필수] 보호자의 정보(보호자 이름, 아이디) [클래스 이용 시][필수] 학교명, 학년, 반 [선택] 보호자와의 관계 [상품 결제 시][필수] 주문자 정보(이름, 전화번호, 휴대전화 번호, 이메일주소), 배송지 정보(이름, 전화번호, 휴대전화 번호, 주소) [상품 결제 취소/환불 시] [필수] 예금주, 계좌번호, 은행명 [체험 상품 결제 시][필수] 참가자 정보(이름, 학년, 성별 등) [유료서비스 이용 시] 신용카드 결제 시(카드사명, 카드번호(일부) 등)휴대전화 결제 시(이동전화번호, 통신사, 결제 승인번호 등)상품권 이용 시(상품권 번호) [고객센터 이용 시] 문의 등록(이메일주소, 사용자 역할, 학년 등)\r\n");
      out.write("                        </div>\r\n");
      out.write("        \r\n");
      out.write("        \r\n");
      out.write("                        <div name=\"infor-text\" class=\"infor-text\">\r\n");
      out.write("                            ※ 고객센터로 문의/신고 유형에 따라 이름, 아이디, 학교 등 여러분이 추가로 입력하는 개인정보가 있을 수 있습니다. 이외에 서비스 이용에 따라 스마트폰 등 단말기 주소록 내에 저장된 연락처 정보(제3자의 전화번호, 이름), 쿠키, 서비스 이용 기록(방문일시, IP, 로그인 시간, 사용자 역할, 국가, 도시 등), 단말기 정보(OS, 화면사이즈, 디바이스 아이디, 폰기종, 단말기 모델명 등), CPU 및 랜카드 정보 등 운영 체제 및 하드웨어 환경 정보 등의 정보가 자동으로 생성되어 수집될 수 있습니다.\r\n");
      out.write("                        </div>\r\n");
      out.write("        \r\n");
      out.write("        \r\n");
      out.write("                    </div>\r\n");
      out.write("        \r\n");
      out.write("                </div>\r\n");
      out.write("\r\n");
      out.write("            </section>\r\n");
      out.write("        </section>\r\n");
      out.write("    </main>\r\n");
      out.write("\r\n");
      out.write("    ");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "/WEB-INF/views/common/footer.jsp", out, false);
      out.write("\r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
